var leng = {
	guardar:"Guardar",
	guardar_cambios:"Guardar todos los cambios",
	hola:"hola",
	hola:"hola",
	imgLogo:"http://social.comsis.mx/templet/images/logo.png",
	no_data_save:"Falta datos para poder guardar",
	drop_image:"Arrastra aqui las imagen",
	no_data_editable:"No hay datos editables en esta sección",
	dato_guardado:"Dato guardado :)",
	sin_titulo_post:"Primero ingrese el titulo del post",
	nombre_nuevo_post:"Nombre del nuevo post",
	seccion_comas:"Indica el nombre de cada sección separado por comas",
	cont_cant:"Indica en número la cantidad de paginas de este elemento a mostrar",
}
var style = {
	h_guardar:"background-color:rgba(30,140,30,0.8);padding:8px;color:#fff;font-size:16px;border:0;border-radius:5px;",
	h_cancelar:"background-color:rgba(140,30,30,0.8);padding:8px;color:#fff;font-size:16px;border:0;border-radius:5px;",
	b_guardar:"background-color:rgba(30,140,30,0.8);padding:8px;color:#fff;font-size:16px;border:0;border-radius:5px;",
	b_cancelar:"background-color:rgba(140,30,30,0.8);padding:8px;color:#fff;font-size:16px;border:0;border-radius:5px;",
	wS_ima:"margin:5px; width:220px; height:60px; background-color:white; border:3px dashed grey;",
	wS_ima_h3:"margin:25px 5px; color:grey; font-size:16px; font-weight:bold;",
	wS_tx:"margin:5px; width:220px; height:30px; background-color:white; font-size:12px;",
	wS_tx_in:"color:#333 !important",
	wS_gu:"background-color:rgba(30,140,30,0.8);padding:4px;color:#fff;font-size:14px;border:0;border-radius:4px;",
	wS_ca:"background-color:rgba(140,30,30,0.8);padding:4px;color:#fff;font-size:14px;border:0;border-radius:4px;",
	wS_he:"margin:5px; width:220px; height:40px; background-color:white;",
	wS_OP:"position:absolute;top:5px;left:70px;padding:5px;border-radius:5px;background-color:rgba(200,200,200,0.7);color:#333;font-size:12px;",
}
